### PR TITLE
Properly `apt-get install inn2` in a GitHub Action.

### PR DESCRIPTION
**Pull request by cclauss**
Demonstrate how to properly `apt-get install inn2` in a GitHub Action. Configure the inn2 instance so that other code can test interactions with the inn2 server.

Much of this project's documentation covers how to build inn2 from source.  It would be helpful if there were working examples of how to properly `apt-get install inn2` in Docker or in a GitHub Action.  I have been struggling to do so for a few hours without success.

We probably need `hostname=localhost` and `domain=localhost.localdomain` but I have been unable to get it right.

> Setting up inn2 (2.6.4-2build4) ...
innconfval: hostname does not resolve or domain not set in inn.conf
dpkg: error processing package inn2 (--configure):
 installed inn2 package post-installation script subprocess returned error exit status 1

### CODE REVIEW

**Comment by Julien-Elie** [comment]
> Demonstrate how to properly `apt-get install inn2` in a GitHub Action.

Couldn't the sample be provided as an example instead of being run at each push or pull request?  Installing the inn2 package provided with stock Ubuntu (currently `inn2-2.6.4-2build4`) is not related to the push or pull request, so I don't think it is worthwhile running it.  Of course I am OK to keep this example, either in `contrib` (like the sample init scripts) or in `.github/workflows` (deactivated).


> We probably need `hostname=localhost` and `domain=localhost.localdomain` but I have been unable to get it right.

The last time I heard someone installing INN in Docker, the trick was to create the configuration file in _/etc/news/inn.conf_ before installing the inn2 package.  You can put `domain: localhost.localdomain` in the configuration file, and the Debian package will no longer fail to install.
A better way would be to use a [custom preseed file](https://wiki.debian.org/DebianInstaller/Preseed) but the current inn2 package does not implement it.

**Comment by cclauss** [comment]
Thanks for this review.  I agree that should be a contrib and we do not need this to run on each PR ___after___ we get it to work.  I need help getting this action to work before we move it to `contrib`.

I will work on your suggestion above this evening.

**Comment by cclauss** [comment]
```
Setting up inn2-inews (2.6.4-2build4) ...
Configuration file '/etc/news/inn.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Keeping old config file as default.
[ ... ]
Setting up inn2 (2.6.4-2build4) ...
innconfval: must set mta in inn.conf
innconfval: must set pathnews in inn.conf
innconfval: must set hismethod in inn.conf
innconfval: ovmethod must be set in inn.conf if enableoverview is true
dpkg: error processing package inn2 (--configure):
 installed inn2 package post-installation script subprocess returned error exit status 1
```

**Comment by Julien-Elie** [comment]
It is a working _inn.conf_ file that should be pre-installed (as the one the inn2 package installs), not an _inn.conf_ file with only one line for the `domain` parameter.

**Comment by cclauss** [comment]
OK...  On my own repo https://github.com/cclauss/inn2-in-docker I am getting closer to a solution.

It works on a `push` on Ubuntu 22.04 but fails on 24.04.  The same solution fails on a `pull_request` on this repo.

In any case, where I could use help now is on the proof that inn2 is functioning properly.  Things like:
* [x] Proof that the inn2 service is running: `systemctl status inn2`
* [ ] Proof of which version of inn2 is running?
* [ ] Short command to add a news article to the inn2 service?
* [ ] Short command to read back that news article?

**Comment by Julien-Elie** [comment]
Oh, great news you managed to make it work!
If you want to run two instances of INN on the same server, you should use different ports for **innd** (119 and 433 for instance), and naturally different installation directories (they cannot use the same _active_ file, news spool, etc.).

```
% innconfval version 
INN 2.8.0 (20240722 prerelease)
% innconfval pathdb       
/home/news/db
```

For commands to test the installation, including posting articles, you may want to see [the autopkgtest script](https://salsa.debian.org/md/inn2/-/blob/master/debian/tests/daemon) Marco wrote for the inn2 Debian package.
If you prefer Python, you could use `nntplib` which provide similar facilities.

Otherwise, using **inews** to post an article, and **sm** to retrieve it would work.

**Comment by cclauss** [comment]
OK.  The GitHub Action works as I wished... On push, pull_request, and workflow_dispatch the Action does:
1. `apt-get install inn2 ` # Almost always works.
2. `systemctl status inn2`
3. Used Python <= 3.12 `nntplib` to run various interactions including posting and reading back an article.

I will move that all into the `contrib` directory if you agree.

---

Now, I would like to use the lessons learned to ___create a Docker image___ but without a `conf.py` file `apt-get install inn2` fails if `hostname` returns `buildkitsandbox` instead of `localhost.localdomain`.

At build-time in both Debian and Ubuntu containers, `hostname` returns `buildkitsandbox`.  Would it be possible to modify inn2's apt-get install script to convert `buildkitsandbox` to `localhost.localdomain`?  It is quite tricky to change the output of `hostname` at Docker build-time.

**Comment by Julien-Elie** [comment]
Hi Christian!  Thanks for your work.

What are the reasons for the failure of `apt-get install inn2`?  Is it something we have a hand on, or a transient failure of GitHub Actions?

`nntplib` is now an externally maintained library here: https://git.cepl.eu/cgit/python/nntplib
It is unfortunately not in PyPi 😞. I hope it will be there again (it had been for a few months but somehow disappeared).

Yes, I agree the sample GitHub Actions could go to `contrib`.  Another possibility would be to keep it there, but deactivated (there may be a command to say so, or suffix it with a `.sample` extension).  Also, the test article file could go to `tests/data/articles/github-action-1`; I think it would be better there (with possible another filename you think more appropriate).

**Comment by Julien-Elie** [comment]
> At build-time in both Debian and Ubuntu containers, `hostname` returns `buildkitsandbox`. Would it be possible to modify the `apt-get install inn2` script to convert `buildkitsandbox` to `localhost.localdomain`?

You should ask the Debian maintainer via opening an inn2 bug for this feature.  A [custom preseed file](https://wiki.debian.org/DebianInstaller/Preseed) could for instance be implemented for setting `domain` in `inn.conf`.

**Comment by cclauss** [comment]
> `nntplib` is now an externally maintained library here: https://git.cepl.eu/cgit/python/nntplib
> It is unfortunately not in PyPi 😞. I hope it will be there again (it had been for a few months but somehow disappeared).

* greenbender/pynntp#8

**Comment by Julien-Elie** [comment]
As `nntplib` is no longer a standard library, the dependency to Python 3.12 will one day no longer work.  Is it still worth including this change to INN in the `contrib` directory?  Wouldn't #313 be better as an example of GitHub Actions?

**Comment by Julien-Elie** [comment]
@cclauss What should be done with this PR?  Couldn't there be an installation of `nntplib` or `pynntp` during the process?
Is this PR still worthwhile compared to #313?

**Comment by cclauss** [comment]
Sorry for the delay.  I will revise these pull requests this week.

**Comment by cclauss** [comment]
Which INN config files must be modified to get two INN2 servers to exchange news articles?
* https://github.com/greenbender/inn-docker/pull/26  Pulling out my hair!!!

**Comment by Julien-Elie** [comment]
Yes, the 3 config files you mentioned (_newsfeeds_, _incoming.conf_ and _innfeed.conf_) are the ones to parameterize in order to feed news articles with NNTP.  There's also the possibility to use UUCP but it is more complicated to set up, and it adds a delay.

Any possibility to find out where the segfault you face with occurs?

**Comment by Julien-Elie** [comment]
Let's commit your current working GitHub Action example to the `contrib` directory.  Thanks again for your work Christian.  In case you have a future update, do not hesitate to open another PR.
